$(document).ready(function(){

	var arrayList = [
			        {"Id": "Agrigento", "Name": "Agrigento"}, 
			        {"Id": "Alessandria", "Name": "Alessandria"},
			        {"Id": "Ancona", "Name": "Ancona"}, 
			        {"Id": "Aosta", "Name": "Aosta"},
			        {"Id": "L'Aquila", "Name": "L'Aquila"}, 
			        {"Id": "Arezzo", "Name": "Arezzo"}, 
			        {"Id": "Ascoli-Piceno", "Name": "Ascoli-Piceno"},
			        {"Id": "Asti", "Name": "Asti"}, 
			        {"Id": "Avellino", "Name": "Avellino"},
			        {"Id": "Bari", "Name": "Bari"}, 
			        {"Id": "Barletta-Andria-Trani", "Name": "Barletta-Andria-Trani"},
			        {"Id": "Belluno", "Name": "Belluno"}, 
			        {"Id": "Benevento", "Name": "Benevento"},
			        {"Id": "Bergamo", "Name": "Bergamo"}, 
			        {"Id": "Biella", "Name": "Biella"},
			        {"Id": "Bologna", "Name": "Bologna"}, 
			        {"Id": "Bolzano", "Name": "Bolzano"},
			        {"Id": "Brescia", "Name": "Brescia"}, 
			        {"Id": "Brindisi", "Name": "Brindisi"},
			        {"Id": "Cagliari", "Name": "Cagliari"}, 
			        {"Id": "Caltanissetta", "Name": "Caltanissetta"},
			        {"Id": "Campobasso", "Name": "Campobasso"}, 
			        {"Id": "Carbonia Iglesias", "Name": "Carbonia Iglesias"},
			        {"Id": "Caserta", "Name": "Caserta"}, 
			        {"Id": "Catania", "Name": "Catania"},
			        {"Id": "Catanzaro", "Name": "Catanzaro"}, 
			        {"Id": "Chieti", "Name": "Chieti"},
			        {"Id": "Como", "Name": "Como"}, 
			        {"Id": "Cosenza", "Name": "Cosenza"},
			        {"Id": "Cremona", "Name": "Cremona"}, 
			        {"Id": "Crotone", "Name": "Crotone"},
			        {"Id": "Cuneo", "Name": "Cuneo"}, 
			        {"Id": "Enna", "Name": "Enna"},
			        {"Id": "Fermo", "Name": "Fermo"}, 
			        {"Id": "Ferrara", "Name": "Ferrara"},
			        {"Id": "Firenze", "Name": "Firenze"}, 
			        {"Id": "Foggia", "Name": "Foggia"},
			        {"Id": "Forli-Cesena", "Name": "Forli-Cesena"}, 
			        {"Id": "Frosinone", "Name": "Frosinone"},
			        {"Id": "Genova", "Name": "Genova"}, 
			        {"Id": "Gorizia", "Name": "Gorizia"},
			        {"Id": "Grosseto", "Name": "Grosseto"}, 
			        {"Id": "Imperia", "Name": "Imperia"},
			        {"Id": "Isernia", "Name": "Isernia"}, 
			        {"Id": "La-Spezia", "Name": "La-Spezia"},
			        {"Id": "Latina", "Name": "Latina"}, 
			        {"Id": "Lecce", "Name": "Lecce"},
			        {"Id": "Lecco", "Lecco": "Livorno"}, 
			        {"Id": "Livorno", "Name": "Livorno"},
			        {"Id": "Lodi", "Name": "Lodi"}, 
			        {"Id": "Lucca", "Name": "Lucca"},
			        {"Id": "Macerata", "Name": "Macerata"}, 
			        {"Id": "Mantova", "Name": "Mantova"},
			        {"Id": "Massa-Carrara", "Name": "Massa-Carrara"}, 
			        {"Id": "Matera", "Matera": "XYZ"},
			        {"Id": "Medio Campidano", "Medio Campidano": "Abc"}, 
			        {"Id": "Messina", "Name": "Messina"},
			        {"Id": "Milano", "Name": "Milano"}, 
			        {"Id": "Modena", "Name": "Modena"},
			        {"Id": "Monza-Brianza", "Name": "Monza-Brianza"}, 
			        {"Id": "Napoli", "Name": "Napoli"},
			        {"Id": "Novara", "Name": "Novara"}, 
			        {"Id": "Nuoro", "Name": "Nuoro"},
			        {"Id": "Ogliastra", "Name": "Ogliastra"}, 
			        {"Id": "Olbia Tempio", "Name": "Olbia Tempio"},
			        {"Id": "Oristano", "Name": "Oristano"}, 
			        {"Id": "Padova", "Name": "Padova"},
			        {"Id": "Palermo", "Name": "Palermo"}, 
			        {"Id": "Parma", "Name": "Parma"},
			        {"Id": "Pavia", "Name": "Pavia"}, 
			        {"Id": "Perugia", "Name": "Perugia"},
			        {"Id": "Pesaro-Urbino", "Name": "Pesaro-Urbino"}, 
			        {"Id": "Pescara", "Name": "Pescara"},
			        {"Id": "Piacenza", "Name": "Piacenza"}, 
			        {"Id": "Pisa", "Name": "Pisa"},
			        {"Id": "Pistoia", "Name": "Pistoia"}, 
			        {"Id": "Pordenone", "Name": "Pordenone"},
			        {"Id": "Potenza", "Name": "Potenza"}, 
			        {"Id": "Prato", "Name": "Prato"},
			        {"Id": "Ragusa", "Name": "Ragusa"}, 
			        {"Id": "Ravenna", "Name": "Ravenna"},
			        {"Id": "Reggio-Calabria", "Name": "Reggio-Calabria"}, 
			        {"Id": "Reggio-Emilia", "Name": "Reggio-Emilia"},
			        {"Id": "Rieti", "Name": "Rieti"}, 
			        {"Id": "Rimini", "Name": "Rimini"},
			        {"Id": "Roma", "Name": "Roma"}, 
			        {"Id": "Rovigo", "Name": "Rovigo"},
			        {"Id": "Salerno", "Name": "Salerno"}, 
			        {"Id": "Sassari", "Name": "Sassari"},
			        {"Id": "Savona", "Name": "Savona"}, 
			        {"Id": "Siena", "Name": "Siena"},
			        {"Id": "Siracusa", "Name": "Siracusa"}, 
			        {"Id": "Sondrio", "Name": "Sondrio"},
			        {"Id": "Taranto", "Name": "Taranto"}, 
			        {"Id": "Teramo", "Name": "Teramo"},
			        {"Id": "Terni", "Name": "Terni"}, 
			        {"Id": "Torino", "Name": "Torino"},
			        {"Id": "Trapani", "Name": "Trapani"},
			        {"Id": "Trento", "Name": "Trento"}, 
			        {"Id": "Treviso", "Name": "Treviso"},
			        {"Id": "Trieste", "Name": "Trieste"}, 
			        {"Id": "Udine", "Name": "Udine"},
			        {"Id": "Varese", "Name": "Varese"}, 
			        {"Id": "Venezia", "Name": "Venezia"},
			        {"Id": "Verbania", "Name": "Verbania"}, 
			        {"Id": "Vercelli", "Name": "Vercelli"},
			        {"Id": "Verona", "Name": "Verona"}, 
			        {"Id": "Vibo-Valentia", "Name": "Vibo-Valentia"},
			        {"Id": "Vicenza", "Name": "Vicenza"}, 
			        {"Id": "Viterbo", "Name": "Viterbo"}
		        ];

	for (var i = 0; i <= arrayList.length; i++) {
		        $('#Provincia').append('<option value="' + arrayList[i].Id + '">' + arrayList[i].Name + '</option>');
	}

}); 